name: CI 

on:
  push:
    branches:
      - stage
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

     
      - name: Output Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
